# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mojolicious-Plugin-Authorization
version:      1.03.02
version_from: 
installdirs:  site
requires:
    Module::Build:                 0.38
    Mojo::Base:                    0
    Mojolicious::Lite:             0
    strict:                        0
    Test::Mojo:                    0
    Test::More:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
