---
abstract: 'A plugin to make authorization a bit easier'
author:
  - 'John Scoles <byterock@hotmail.com>'
build_requires:
  Module::Build: 0.38
  Mojolicious::Lite: 0
  Test::Mojo: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Authorization
no_index:
  directory:
    - t
    - inc
requires:
  Mojo::Base: 0
version: 1.0301
